version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "ktr0731"
    default_labels:
      - "update"
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
